services:
  seed:
    image: kadlab:latest
    command: ["serve",
      "-bind","0.0.0.0:9999",
      "-adv","seed:9999",
      "-ttl","30s",
      "-refresh","15s",
      "-http=:8080"
    ]
    networks: [kadnet]
    ports: ["18080:8080"]
    restart: unless-stopped

  node:
    image: kadlab:latest
    command: ["serve",
      "-bind","0.0.0.0:9999",
      "-seeds","seed:9999",
      "-ttl","30s",
      "-refresh","15s",
      "-http=:8080"
    ]
    networks: [kadnet]
    restart: unless-stopped

networks:
  kadnet:
    driver: bridge
