# docker-compose.yml
# services:
#   node:
#     image: kadlab:latest           # or use "build: ." if you prefer
#     command: ["/app/node", "-bind", ":9999"]
#     environment:
#       - INSTANCE=${HOSTNAME:-node}
#     networks: [kadnet]
#     restart: unless-stopped

# networks:
#   kadnet:
#     driver: bridge

# docker-compose.yml
# docker-compose.yml
services:
  seed:
    image: kadlab:latest
    command: ["serve","-bind","0.0.0.0:9999","-adv","seed:9999","-ttl","30s","-refresh","15s"]
    networks: [kadnet]

  node:
    image: kadlab:latest
    command: ["serve","-bind","0.0.0.0:9999","-seeds","seed:9999","-adv","${HOSTNAME}:9999","-ttl","30s","-refresh","15s"]
    networks: [kadnet]

networks:
  kadnet:
    driver: bridge


# docker-compose.yml

